### PR TITLE
Fix add.js

### PR DESCRIPTION
**Pull request by RealTitanGod**
Mine never worked so I started digging into why it failed to start playing. The interaction.options.getMessage leads to https://discord.js.org/#/docs/discord.js/main/class/Message which we just need content from. I added the const tr = track.tracks[0]; from play.js since I was getting undefined from track.title, that seemed to fix it.

### CODE REVIEW

**Comment by whirlxd** [comment]
ok 
ill look into it and merge when i get the time

**Comment by whirlxd** [comment]
@RealTitanGod aight it looks fine but for the sake of it can you send me a an example of the now working command 
ill merge it then

**Comment by RealTitanGod** [comment]
@Whirl21 Sure:
Screenshot_63

**Comment by whirlxd** [comment]
thanks
merged

**Pull request merged**
